version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: computadoras-db
    environment:
      POSTGRES_DB: computadorasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: kareeeels/backend:latest
    container_name: computadoras-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/computadorasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped

volumes:
  postgres_data:
